### ISSUE TITLE
Add dockerfile or docker-compose.yml for simple project starting

### ISSUE THREAD

**Issue by Skeletonek** [matiqn18/DinnersProject#1]
Hello

I wanted to have a quick look into your project, but startup configuration is quite time consuming.

It would be very nice if a dockerfile or docker-compose.yml could be available from this repository to quickly boot up a container with running project.

Have a great day

**Comment by matiqn18** [comment]
Hello,

Thank you for your interest in the project!

I've added Docker support to the repository to simplify the setup process. You can find the Docker configuration in the docker branch. It includes both the Dockerfile and docker-compose.yml files, which allow you to quickly boot up a container with the running project.

If you have any questions or run into any issues, please feel free to ask.

Have a great day!
